"""Provider interfaces and model-spec registry."""

from genblaze_core.providers.base import (
    BaseProvider,
    ProviderCapabilities,
    SubmitResult,
    SyncProvider,
    validate_asset_url,
    validate_chain_input_url,
)
from genblaze_core.providers.constraints import (
    Constraint,
    implies,
    mutually_exclusive,
    required_one_of,
    requires_together,
)
from genblaze_core.providers.discovery import (
    DEFAULT_TTL_SECONDS,
    DiscoveryResult,
    DiscoveryStatus,
)
from genblaze_core.providers.family import (
    MAX_PROVIDER_FAMILIES,
    DiscoverySupport,
    FamilyMatch,
    FamilyProbe,
    LiveProbeResult,
    ModelFamily,
)
from genblaze_core.providers.input_mapping import (
    InputMapping,
    chain_routers,
    route_audio,
    route_by_media_type,
    route_images,
    route_keyframes,
    route_video,
)
from genblaze_core.providers.model_registry import (
    EMPTY_REGISTRY,
    ModelRegistry,
    compute_cost,
)
from genblaze_core.providers.params import (
    ParamSurface,
    modality_defaults,
    register_modality_default,
)
from genblaze_core.providers.pricing import (
    PricingContext,
    PricingStrategy,
    bucketed_by_duration,
    by_model_and_param,
    by_param,
    first_match,
    per_input_chars,
    per_output_second,
    per_response_metric,
    per_unit,
    tiered,
)
from genblaze_core.providers.probe import ProbeResult, ProbeStatus
from genblaze_core.providers.registry import (
    CREDENTIAL_KWARGS,
    discover_providers,
    instantiate_with_credential,
)
from genblaze_core.providers.retry import (
    MAX_RETRY_AFTER_SEC,
    PRE_RESPONSE_EXCEPTIONS,
    RetryPolicy,
    retry_after_from_response,
)
from genblaze_core.providers.spec import (
    FALLBACK_SPEC,
    ArraySchema,
    BoolSchema,
    EnumSchema,
    FloatSchema,
    IntSchema,
    ModelSpec,
    ParamSchema,
    StringSchema,
)
from genblaze_core.providers.validation import (
    ValidationOutcome,
    ValidationResult,
    ValidationSource,
)

__all__ = [
    "CREDENTIAL_KWARGS",
    "DEFAULT_TTL_SECONDS",
    "EMPTY_REGISTRY",
    "FALLBACK_SPEC",
    "MAX_PROVIDER_FAMILIES",
    "MAX_RETRY_AFTER_SEC",
    "PRE_RESPONSE_EXCEPTIONS",
    "ArraySchema",
    "BaseProvider",
    "BoolSchema",
    "Constraint",
    "DiscoveryResult",
    "DiscoveryStatus",
    "DiscoverySupport",
    "EnumSchema",
    "FamilyMatch",
    "FamilyProbe",
    "FloatSchema",
    "InputMapping",
    "IntSchema",
    "LiveProbeResult",
    "ModelFamily",
    "ModelRegistry",
    "ModelSpec",
    "ParamSchema",
    "ParamSurface",
    "PricingContext",
    "PricingStrategy",
    "ProbeResult",
    "ProbeStatus",
    "ProviderCapabilities",
    "RetryPolicy",
    "StringSchema",
    "SubmitResult",
    "SyncProvider",
    "ValidationOutcome",
    "ValidationResult",
    "ValidationSource",
    "bucketed_by_duration",
    "by_model_and_param",
    "by_param",
    "chain_routers",
    "compute_cost",
    "discover_providers",
    "first_match",
    "implies",
    "instantiate_with_credential",
    "modality_defaults",
    "mutually_exclusive",
    "per_input_chars",
    "per_output_second",
    "per_response_metric",
    "per_unit",
    "register_modality_default",
    "required_one_of",
    "requires_together",
    "retry_after_from_response",
    "route_audio",
    "route_by_media_type",
    "route_images",
    "route_keyframes",
    "route_video",
    "tiered",
    "validate_asset_url",
    "validate_chain_input_url",
]
