"""Provider interfaces and model-spec registry."""

from genblaze_core.providers.base import (
    BaseProvider,
    ProviderCapabilities,
    SubmitResult,
    SyncProvider,
    validate_asset_url,
    validate_chain_input_url,
)
from genblaze_core.providers.constraints import (
    Constraint,
    implies,
    mutually_exclusive,
    required_one_of,
    requires_together,
)
from genblaze_core.providers.input_mapping import (
    InputMapping,
    chain_routers,
    route_audio,
    route_by_media_type,
    route_images,
    route_keyframes,
    route_video,
)
from genblaze_core.providers.model_registry import (
    EMPTY_REGISTRY,
    ModelRegistry,
    compute_cost,
)
from genblaze_core.providers.params import (
    ParamSurface,
    modality_defaults,
    register_modality_default,
)
from genblaze_core.providers.pricing import (
    PricingContext,
    PricingStrategy,
    bucketed_by_duration,
    by_model_and_param,
    by_param,
    first_match,
    per_input_chars,
    per_output_second,
    per_response_metric,
    per_unit,
    tiered,
)
from genblaze_core.providers.probe import ProbeResult, ProbeStatus
from genblaze_core.providers.registry import (
    CREDENTIAL_KWARGS,
    discover_providers,
    instantiate_with_credential,
)
from genblaze_core.providers.spec import (
    FALLBACK_SPEC,
    ArraySchema,
    BoolSchema,
    EnumSchema,
    FloatSchema,
    IntSchema,
    ModelSpec,
    ParamSchema,
    StringSchema,
)

__all__ = [
    "CREDENTIAL_KWARGS",
    "EMPTY_REGISTRY",
    "FALLBACK_SPEC",
    "ArraySchema",
    "BaseProvider",
    "BoolSchema",
    "Constraint",
    "EnumSchema",
    "FloatSchema",
    "InputMapping",
    "IntSchema",
    "ModelRegistry",
    "ModelSpec",
    "ParamSchema",
    "ParamSurface",
    "PricingContext",
    "PricingStrategy",
    "ProbeResult",
    "ProbeStatus",
    "ProviderCapabilities",
    "StringSchema",
    "SubmitResult",
    "SyncProvider",
    "bucketed_by_duration",
    "by_model_and_param",
    "by_param",
    "chain_routers",
    "compute_cost",
    "discover_providers",
    "first_match",
    "implies",
    "instantiate_with_credential",
    "modality_defaults",
    "mutually_exclusive",
    "per_input_chars",
    "per_output_second",
    "per_response_metric",
    "per_unit",
    "register_modality_default",
    "required_one_of",
    "requires_together",
    "route_audio",
    "route_by_media_type",
    "route_images",
    "route_keyframes",
    "route_video",
    "tiered",
    "validate_asset_url",
    "validate_chain_input_url",
]
