#!/usr/bin/env python3
"""Auto-generate the per-provider model matrix shown in the README.

Walks every entry-point-discovered provider, reads its default
``ModelRegistry``, and emits a markdown table per provider with columns:
slug · modality · pricing · allowed params · notes.

Two modes:

* Default — write/overwrite ``docs/reference/model-matrix.md``.
* ``--readme`` — also splice the rendered matrix into the README between
  ``<!-- MODEL_MATRIX_START -->`` and ``<!-- MODEL_MATRIX_END -->`` markers.
* ``--check`` — exit non-zero if either output is stale (CI staleness gate).

Pricing is rendered by sampling ``BaseProvider.estimate_cost(model_id)`` so
per-second strategies are surfaced (``$0.052/s``) rather than misreported.
"""

from __future__ import annotations

import argparse
import sys
from decimal import Decimal
from pathlib import Path

from genblaze_core.providers import discover_providers, instantiate_with_credential
from genblaze_core.providers.base import BaseProvider
from genblaze_core.providers.spec import ModelSpec

_REPO_ROOT = Path(__file__).resolve().parent.parent
_DEFAULT_OUT = _REPO_ROOT / "docs" / "reference" / "model-matrix.md"
_README = _REPO_ROOT / "README.md"
_START_MARKER = "<!-- MODEL_MATRIX_START -->"
_END_MARKER = "<!-- MODEL_MATRIX_END -->"


def _format_pricing(provider: BaseProvider, model_id: str, spec: ModelSpec) -> str:
    if spec.pricing is None:
        return "—"
    flat = provider.estimate_cost(model_id)
    if flat is not None and flat > Decimal("0"):
        return f"${flat:.4f}/asset"
    # Try a per-second probe with duration=1 to detect per-second pricing.
    one_sec = provider.estimate_cost(model_id, params={"duration": 1})
    if one_sec is not None and one_sec > Decimal("0"):
        return f"${one_sec:.4f}/s"
    return "varies"


def _format_params(spec: ModelSpec) -> str:
    if spec.param_allowlist is None:
        return "_pass-through_"
    return ", ".join(sorted(spec.param_allowlist))


def _format_notes(spec: ModelSpec) -> str:
    notes: list[str] = []
    if spec.extras.get("suspected_dead"):
        notes.append("⚠ suspected_dead")
    if spec.deprecated_aliases:
        # Show up to 3 to keep tables readable.
        shown = sorted(spec.deprecated_aliases)[:3]
        more = (
            "" if len(spec.deprecated_aliases) <= 3 else f" (+{len(spec.deprecated_aliases) - 3})"
        )
        notes.append("aliases: " + ", ".join(f"`{a}`" for a in shown) + more)
    return "; ".join(notes) or ""


def _render_provider(name: str, cls: type[BaseProvider]) -> str:
    provider = instantiate_with_credential(cls, "matrix-render")
    rows = [
        f"### `{name}`",
        "",
        "| Model | Modality | Pricing | Allowed params | Notes |",
        "|---|---|---|---|---|",
    ]
    for model_id, spec in provider.models.items():
        rows.append(
            f"| `{model_id}` "
            f"| {spec.modality.value if spec.modality else '—'} "
            f"| {_format_pricing(provider, model_id, spec)} "
            f"| {_format_params(spec)} "
            f"| {_format_notes(spec)} |"
        )
    rows.append("")
    return "\n".join(rows)


def render_full_matrix() -> str:
    discovered = discover_providers()
    blocks: list[str] = [
        "<!-- AUTO-GENERATED by tools/gen_model_matrix.py — do not edit by hand. -->",
        "# Genblaze model matrix",
        "",
        "Slug, modality, pricing, and allowed-param surface for every model in the",
        "default registry of every installed connector. Regenerate with:",
        "",
        "```bash",
        "python tools/gen_model_matrix.py",
        "```",
        "",
    ]
    for name in sorted(discovered):
        blocks.append(_render_provider(name, discovered[name]))
    return "\n".join(blocks).rstrip() + "\n"


def _splice_into_readme(rendered: str) -> str:
    if not _README.exists():
        raise SystemExit(f"README not found at {_README}")
    src = _README.read_text()
    if _START_MARKER not in src or _END_MARKER not in src:
        raise SystemExit(
            f"README is missing {_START_MARKER!r} / {_END_MARKER!r} markers; "
            "add them to enable the splice."
        )
    pre, _, rest = src.partition(_START_MARKER)
    _, _, post = rest.partition(_END_MARKER)
    return f"{pre}{_START_MARKER}\n{rendered}\n{_END_MARKER}{post}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate the per-provider model matrix from registered ModelSpecs."
    )
    parser.add_argument("--out", type=Path, default=_DEFAULT_OUT)
    parser.add_argument(
        "--readme",
        action="store_true",
        help="Also splice the matrix into README.md between MODEL_MATRIX markers.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the on-disk matrix or README is stale (CI gate).",
    )
    args = parser.parse_args(argv)

    rendered = render_full_matrix()
    args.out.parent.mkdir(parents=True, exist_ok=True)

    drift = False
    if args.check and args.out.exists() and args.out.read_text() != rendered:
        print(f"STALE: {args.out.relative_to(_REPO_ROOT)} is out of date.", file=sys.stderr)
        drift = True
    elif not args.check:
        args.out.write_text(rendered)
        print(f"Wrote {args.out.relative_to(_REPO_ROOT)}")

    if args.readme:
        new_readme = _splice_into_readme(rendered)
        if args.check and _README.read_text() != new_readme:
            print("STALE: README.md model-matrix block is out of date.", file=sys.stderr)
            drift = True
        elif not args.check:
            _README.write_text(new_readme)
            print(f"Spliced matrix into {_README.relative_to(_REPO_ROOT)}")

    if drift:
        print("Run `python tools/gen_model_matrix.py --readme` to refresh.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
